language: java
jdk:
  - oraclejdk8
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
cache:
  directories:
    - ~/.m2/repository
after_success:
  - ./.travis/before-deploy.sh
deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: ddebree/game-ai
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: ddebree/game-ai
      tags: true
      jdk: oraclejdk8