language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - ~/.m2/repository
deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: ddebree/game-ai
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: ddebree/game-ai
      tags: true
      jdk: oraclejdk8